# Importing movies from 2019

In [89]:
import pandas as pd
import numpy as np

In [97]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2019"
df1 = pd.read_html(link, header=0)[2]
df2 = pd.read_html(link, header=0)[3]
df3 = pd.read_html(link, header=0)[4]
df4 = pd.read_html(link, header=0)[5]

In [107]:
df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

In [108]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.
0,JANUARY,4,Escape Room,Columbia Pictures,"Adam Robitel (director); Bragi F. Schut, Maria...",[2]
1,JANUARY,4,Rust Creek,IFC Films,Jen McGowan (director); Julie Lipson (screenpl...,[3]
2,JANUARY,4,American Hangman,Hangman Justice Productions,Wilson Coneybeare (director/screenplay); Donal...,[4]
3,JANUARY,11,A Dog's Way Home,Columbia Pictures,Charles Martin Smith (director); W. Bruce Came...,[5]
4,JANUARY,11,The Upside,STX Entertainment,Neil Burger (director); Jon Hartmere (screenpl...,[6]
...,...,...,...,...,...,...
239,DECEMBER,25,Little Women,Columbia Pictures / Regency Enterprises,Greta Gerwig (director/screenplay); Saoirse Ro...,[223]
240,DECEMBER,25,1917,Universal Pictures / DreamWorks Pictures / Ent...,Sam Mendes (director/screenplay); Krysty Wilso...,[224]
241,DECEMBER,25,Just Mercy,Warner Bros. Pictures / Participant Media,"Destin Daniel Cretton (director/screenplay), A...",[225]
242,DECEMBER,27,Clemency,Neon,Chinonye Chukwu (director/screenplay); Alfre W...,[226]
243,DECEMBER,27,Apparition,Vertical Pictures,Waymon Boone (director/screenplay); Mena Suvar...,[227]

In [109]:
from omdbapi.movie_search import GetMovie
import json
import requests

In [110]:
genres = []
for i in range(243):
    movie = GetMovie(title=df['Title'][i], api_key='e3fc1d3f', plot='full')
    data = movie.get_data('Genre')
    genres.append(data)

In [111]:
from pandas import DataFrame
df3 = DataFrame(genres,columns=['Genre'])

In [112]:
df['genres'] = df3

In [113]:
df_en = df[['Title','Cast and crew','genres']]

In [114]:
df_en

,Title,Cast and crew,genres
0,Escape Room,"Adam Robitel (director); Bragi F. Schut, Maria...","Action, Adventure, Horror, Mystery, Thriller"
1,Rust Creek,Jen McGowan (director); Julie Lipson (screenpl...,"Crime, Drama, Thriller"
2,American Hangman,Wilson Coneybeare (director/screenplay); Donal...,Thriller
3,A Dog's Way Home,Charles Martin Smith (director); W. Bruce Came...,"Adventure, Drama, Family"
4,The Upside,Neil Burger (director); Jon Hartmere (screenpl...,"Comedy, Drama"
...,...,...,...
239,Little Women,Greta Gerwig (director/screenplay); Saoirse Ro...,"Drama, Romance"
240,1917,Sam Mendes (director/screenplay); Krysty Wilso...,"Drama, Thriller, War"
241,Just Mercy,"Destin Daniel Cretton (director/screenplay), A...","Biography, Crime, Drama"
242,Clemency,Chinonye Chukwu (director/screenplay); Alfre W...,Drama
243,Apparition,Waymon Boone (director/screenplay); Mena Suvar...,NaN

In [115]:
def get_director(x):
    if " (director)" in x:
        return x.split(" (director)")[0]
    elif " (directors)" in x:
        return x.split(" (directors)")[0]
    else:
        return x.split(" (director/screenplay)")[0]

In [116]:
df_en['director_name'] = df_en['Cast and crew'].map(lambda x: get_director(x))

<ipython-input-116-acbd25dcf5d9>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_en['director_name'] = df_en['Cast and crew'].map(lambda x: get_director(x))

In [117]:
def get_actor1(x):
    return ((x.split("screenplay); ")[-1]).split(", ")[0])

In [118]:
df_en['actor_1_name'] = df_en['Cast and crew'].map(lambda x: get_actor1(x))

<ipython-input-118-9b2cd0307416>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_en['actor_1_name'] = df_en['Cast and crew'].map(lambda x: get_actor1(x))

In [119]:
def get_actor2(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 2:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[1])

In [120]:
df_en['actor_2_name'] = df_en['Cast and crew'].map(lambda x: get_actor2(x))

<ipython-input-120-1978d7b65e8a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_en['actor_2_name'] = df_en['Cast and crew'].map(lambda x: get_actor2(x))

In [121]:
def get_actor3(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 3:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[2])

In [122]:
df_en['actor_3_name'] = df_en['Cast and crew'].map(lambda x: get_actor3(x))

In [123]:
df_en = df_en.rename(columns={'Title':'movie_title'})

In [124]:
new_df19 = df_en.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [125]:
new_df19['actor_2_name'] = new_df19['actor_2_name'].replace(np.nan, 'unknown')
new_df19['actor_3_name'] = new_df19['actor_3_name'].replace(np.nan, 'unknown')
new_df19['movie_title'] = new_df19['movie_title'].str.lower()

In [126]:
new_df19['comb'] = new_df19['actor_1_name'] + ' ' + new_df19['actor_2_name'] + ' '+ new_df19['actor_3_name'] + ' '+ new_df19['director_name'] +' ' + new_df19['genres']

In [127]:
new_df19

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Adam Robitel,Taylor Russell,Logan Miller,Deborah Ann Woll,"Action, Adventure, Horror, Mystery, Thriller",escape room,Taylor Russell Logan Miller Deborah Ann Woll A...
1,Jen McGowan,Hermione Corfield,Jay Paulson,Sean O'Bryan,"Crime, Drama, Thriller",rust creek,Hermione Corfield Jay Paulson Sean O'Bryan Jen...
2,Wilson Coneybeare,Donald Sutherland,Vincent Kartheiser,Oliver Dennis,Thriller,american hangman,Donald Sutherland Vincent Kartheiser Oliver De...
3,Charles Martin Smith,Bryce Dallas Howard,Edward James Olmos,Alexandra Shipp,"Adventure, Drama, Family",a dog's way home,Bryce Dallas Howard Edward James Olmos Alexand...
4,Neil Burger,Bryan Cranston,Kevin Hart,Nicole Kidman,"Comedy, Drama",the upside,Bryan Cranston Kevin Hart Nicole Kidman Neil B...
...,...,...,...,...,...,...,...
239,Greta Gerwig,Saoirse Ronan,Emma Watson,Florence Pugh,"Drama, Romance",little women,Saoirse Ronan Emma Watson Florence Pugh Greta ...
240,Sam Mendes,George MacKay,Dean-Charles Chapman,Mark Strong,"Drama, Thriller, War",1917,George MacKay Dean-Charles Chapman Mark Strong...
241,Destin Daniel Cretton,Michael B. Jordan,Jamie Foxx,Brie Larson,"Biography, Crime, Drama",just mercy,Michael B. Jordan Jamie Foxx Brie Larson Desti...
242,Chinonye Chukwu,Alfre Woodard,Wendell Pierce,Aldis Hodge,Drama,clemency,Alfre Woodard Wendell Pierce Aldis Hodge Chino...
243,Waymon Boone,Mena Suvari,Kevin Pollak,unknown,NaN,apparition,NaN

In [47]:
link = "https://en.wikipedia.org/wiki/List_of_Bollywood_films_of_2019"
df1 = pd.read_html(link, header=0)[3]
df2 = pd.read_html(link, header=0)[4]
df3 = pd.read_html(link, header=0)[5]
df4 = pd.read_html(link, header=0)[6]

In [50]:
df_b = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

In [51]:
df_b

,Opening,Opening.1,Title,Director,Cast,Studio (production house),Ref.
0,JAN,4.0,Salt Bridge,Abhijit Deonath,Rajeev KhandelwalChelsie Preston CrayfordUsha ...,NaN,[13]
1,JAN,9.0,Cabaret,Kaustav Narayan Niyogi,Richa ChaddaGulshan DevaiahS. Sreesanth,"Fisheye Network Private Limited, T-Series",[14]
2,JAN,11.0,Uri: The Surgical Strike,Aditya Dhar,Vicky KaushalMohit RainaParesh RawalYami Gautam,RSVP Movies,[15][16]
3,JAN,11.0,Battalion 609,Brijesh Batuknath Tripathi,Shoaib IbrahimElena KazanFarnaz ShettyVishwas ...,N.J Lalwani Films,[17][18][19]
4,JAN,11.0,The Accidental Prime Minister,Vijay Ratnakar Gutte,Anupam KherAkshaye KhannaSuzanne BernertAahana...,Bohra Bros Production,[20][21]
...,...,...,...,...,...,...,...
120,DEC,13.0,Mardaani 2,Gopi Puthran,Rani MukerjiVikram Singh ChauhanShruti BapnaRa...,Yash Raj Films,[180]
121,DEC,13.0,The Body,Jeethu Joseph,Emraan HashmiRishi KapoorVedhikaSobhita Dhulipala,Viacom18 Motion Pictures,[181]
122,DEC,20.0,Dabangg 3,Prabhu Deva,Salman KhanSonakshi SinhaSudeepSaiee Manjrekar...,"Arbaaz Khan Productions, Salman Khan Films",[182]
123,DEC,25.0,Happi,Bhavna Talwar,Pankaj KapoorSupriya PathakHrishitaa Bhatt,"Vistaar Film Fund, WSG Pictures",[183]
124,DEC,27.0,Good Newwz,Raj Mehta,Akshay KumarKareena KapoorDiljit DosanjhKiara ...,"Dharma Productions, Cape Of Good Films",[184]

In [52]:
from omdbapi.movie_search import GetMovie
import json
import requests

In [53]:
genres = []
for i in range(104):
    movie = GetMovie(title=df_b['Title'][i], api_key='e3fc1d3f', plot='full')
    data = movie.get_data('Genre')
    genres.append(data)

In [54]:
from pandas import DataFrame
df4 = DataFrame(genres,columns=['Genre'])

In [55]:
df_b['genres'] = df4
df_b['Cast and crew'] = df_b['Cast']

In [56]:
df_en = df_b[['Title','Director','Cast and crew','genres']]

In [57]:
df_en['Cast and crew'] = df_en['Cast and crew'].str.replace( r"([A-Z])", r" \1").str.strip()

<ipython-input-57-add6444aa4b9>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_en['Cast and crew'] = df_en['Cast and crew'].str.replace( r"([A-Z])", r" \1").str.strip()

In [58]:
df_en

,Title,Director,Cast and crew,genres
0,Salt Bridge,Abhijit Deonath,Rajeev Khandelwal Chelsie Preston Crayford ...,Drama
1,Cabaret,Kaustav Narayan Niyogi,Richa Chadda Gulshan Devaiah S. Sreesanth,"Drama, Music, Musical"
2,Uri: The Surgical Strike,Aditya Dhar,Vicky Kaushal Mohit Raina Paresh Rawal Yami...,"Action, Drama, War"
3,Battalion 609,Brijesh Batuknath Tripathi,Shoaib Ibrahim Elena Kazan Farnaz Shetty Vi...,War
4,The Accidental Prime Minister,Vijay Ratnakar Gutte,Anupam Kher Akshaye Khanna Suzanne Bernert ...,"Biography, Drama"
...,...,...,...,...
120,Mardaani 2,Gopi Puthran,Rani Mukerji Vikram Singh Chauhan Shruti B...,NaN
121,The Body,Jeethu Joseph,Emraan Hashmi Rishi Kapoor Vedhika Sobhita ...,NaN
122,Dabangg 3,Prabhu Deva,Salman Khan Sonakshi Sinha Sudeep Saiee Man...,NaN
123,Happi,Bhavna Talwar,Pankaj Kapoor Supriya Pathak Hrishitaa Bhatt,NaN
124,Good Newwz,Raj Mehta,Akshay Kumar Kareena Kapoor Diljit Dosanjh ...,NaN

In [59]:
df_en.to_csv("2019_Movies.csv")

In [60]:
df10 = pd.read_csv("2019_Movies_cleaned.csv")
df10.head()

,Unnamed: 0,movie_title,director_name,Cast and crew,genres,actor_1_name,actor_2_name,actor_3_name
0,0,Salt Bridge,Abhijit Deonath,Rajeev Khandelwal Chelsie Preston Crayford ...,Drama,Rajeev Khandelwal,Chelsie Preston,Usha Jadhav
1,1,Cabaret,Kaustav Narayan Niyogi,Richa Chadda Gulshan Devaiah S. Sreesanth,"Drama, Music, Musical",Richa Chadda,Gulshan Devaiah,S. Sreesanth
2,2,Uri: The Surgical Strike,Aditya Dhar,Vicky Kaushal Mohit Raina Paresh Rawal Yami...,"Action, Drama, War",Vicky Kaushal,Yami Gautam,Paresh Rawal
3,3,Battalion 609,Brijesh Batuknath Tripathi,Shoaib Ibrahim Elena Kazan Farnaz Shetty Vi...,War,Shoaib Ibrahim,Elena Kazan,Farnaz Shetty
4,4,The Accidental Prime Minister,Vijay Ratnakar Gutte,Anupam Kher Akshaye Khanna Suzanne Bernert ...,"Biography, Drama",Anupam Kher,Akshaye Khanna,Suzanne Bernert

In [61]:
hnew_df19 = df10.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [62]:
hnew_df19['actor_2_name'] = hnew_df19['actor_2_name'].replace(np.nan, 'unknown')
hnew_df19['actor_3_name'] = hnew_df19['actor_3_name'].replace(np.nan, 'unknown')
hnew_df19['movie_title'] = hnew_df19['movie_title'].str.lower()

In [63]:
hnew_df19['comb'] = hnew_df19['actor_1_name'] + ' ' + hnew_df19['actor_2_name'] + ' '+ hnew_df19['actor_3_name'] + ' '+ hnew_df19['director_name'] +' ' + hnew_df19['genres']

In [130]:
df_2019 = new_df19.append(hnew_df19,ignore_index=True)

In [131]:
df_2019

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Adam Robitel,Taylor Russell,Logan Miller,Deborah Ann Woll,"Action, Adventure, Horror, Mystery, Thriller",escape room,Taylor Russell Logan Miller Deborah Ann Woll A...
1,Jen McGowan,Hermione Corfield,Jay Paulson,Sean O'Bryan,"Crime, Drama, Thriller",rust creek,Hermione Corfield Jay Paulson Sean O'Bryan Jen...
2,Wilson Coneybeare,Donald Sutherland,Vincent Kartheiser,Oliver Dennis,Thriller,american hangman,Donald Sutherland Vincent Kartheiser Oliver De...
3,Charles Martin Smith,Bryce Dallas Howard,Edward James Olmos,Alexandra Shipp,"Adventure, Drama, Family",a dog's way home,Bryce Dallas Howard Edward James Olmos Alexand...
4,Neil Burger,Bryan Cranston,Kevin Hart,Nicole Kidman,"Comedy, Drama",the upside,Bryan Cranston Kevin Hart Nicole Kidman Neil B...
...,...,...,...,...,...,...,...
359,Gopi Puthran,Rani Mukerji,Vikram Singh Chauhan,Shruti Bapna,"Drama, Mystery",mardaani 2,Rani Mukerji Vikram Singh Chauhan Shruti B...
360,Jeethu Joseph,Emraan Hashmi,Rishi Kapoor,Vedhika,"Drama, Mystery",the body,Emraan Hashmi Rishi Kapoor Vedhika Jeethu Jo...
361,Prabhu Deva,Salman Khan,Sonakshi Sinha,Sudeep,"Action, Comedy",dabangg 3,Salman Khan Sonakshi Sinha Sudeep Prabhu Dev...
362,Bhavna Talwar,Pankaj Kapoor,Supriya Pathak,Hrishitaa Bhatt,Drama,happi,Pankaj Kapoor Supriya Pathak Hrishitaa Bha...
363,Raj Mehta,Akshay Kumar,Kareena Kapoor,Diljit Dosanjh,"Comedy, Drama",good newwz,Akshay Kumar Kareena Kapoor Diljit Dosanj...

In [132]:
df_2019.to_csv("2019_Films_All.csv")

## 2020 Movies

In [184]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2020"
df1 = pd.read_html(link, header=0)[3]
df2 = pd.read_html(link, header=0)[4]
df3 = pd.read_html(link, header=0)[5]
df4 = pd.read_html(link, header=0)[6]

In [185]:
df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

In [186]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.
0,JANUARY,3,The Grudge,Screen Gems / Stage 6 Films / Ghost House Pict...,Nicolas Pesce (director/screenplay); Andrea Ri...,[2]
1,JANUARY,10,Underwater,20th Century Fox / TSG Entertainment / Chernin...,"William Eubank (director); Brian Duffield, Ada...",[3]
2,JANUARY,10,Like a Boss,Paramount Pictures,"Miguel Arteta (director); Sam Pitman, Adam Col...",[4]
3,JANUARY,10,Three Christs,IFC Films,Jon Avnet (director/screenplay); Eric Nazarian...,NaN
4,JANUARY,10,Inherit the Viper,Barry Films / Tycor International Film Company,Anthony Jerjen (director); Andrew Crabtree (sc...,[5]
...,...,...,...,...,...,...
265,DECEMBER,25,We Can Be Heroes,Netflix / Troublemaker Studios,Robert Rodriguez (director/screenplay); Priyan...,[237]
266,DECEMBER,25,News of the World,Universal Pictures / Perfect World Pictures / ...,Paul Greengrass (director/screenplay); Luke Da...,[238]
267,DECEMBER,25,One Night in Miami,Amazon Studios,Regina King (director); Kemp Powers (screenpla...,[239]
268,DECEMBER,25,Promising Young Woman,Focus Features / FilmNation Entertainment,Emerald Fennell (director/screenplay); Carey M...,[240]
269,DECEMBER,30,Pieces of a Woman,Netflix / Bron Studios,KornÃ©l MundruczÃ³ (director); Kata WÃ©ber (scree...,[241]

In [187]:
from omdbapi.movie_search import GetMovie
import json
import requests

In [188]:
genres = []
for i in range(269):
    movie = GetMovie(title=df['Title'][i], api_key='e3fc1d3f', plot='full')
    data = movie.get_data('Genre')
    genres.append(data)

In [189]:
from pandas import DataFrame
df3 = DataFrame(genres,columns=['Genre'])

In [190]:
df['genres'] = df3

In [191]:
df_en = df[['Title','Cast and crew','genres']]

In [192]:
def get_director(x):
    if " (director)" in x:
        return x.split(" (director)")[0]
    elif " (directors)" in x:
        return x.split(" (directors)")[0]
    else:
        return x.split(" (director/screenplay)")[0]

In [193]:
df_en['director_name'] = df_en['Cast and crew'].map(lambda x: get_director(x))

<ipython-input-193-acbd25dcf5d9>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_en['director_name'] = df_en['Cast and crew'].map(lambda x: get_director(x))

In [194]:
def get_actor1(x):
    return ((x.split("screenplay); ")[-1]).split(", ")[0])

In [195]:
df_en['actor_1_name'] = df_en['Cast and crew'].map(lambda x: get_actor1(x))

<ipython-input-195-9b2cd0307416>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_en['actor_1_name'] = df_en['Cast and crew'].map(lambda x: get_actor1(x))

In [196]:
def get_actor2(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 2:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[1])

In [197]:
df_en['actor_2_name'] = df_en['Cast and crew'].map(lambda x: get_actor2(x))

<ipython-input-197-1978d7b65e8a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_en['actor_2_name'] = df_en['Cast and crew'].map(lambda x: get_actor2(x))

In [198]:
def get_actor3(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 3:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[2])

In [199]:
df_en['actor_3_name'] = df_en['Cast and crew'].map(lambda x: get_actor3(x))

In [200]:
df_en = df_en.rename(columns={'Title':'movie_title'})

In [201]:
new_df20 = df_en.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [203]:
new_df20['comb'] = new_df20['actor_1_name'] + ' ' + new_df20['actor_2_name'] + ' '+ new_df20['actor_3_name'] + ' '+ new_df20['director_name'] +' ' + new_df20['genres']

In [204]:
new_df20

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Nicolas Pesce,Andrea Riseborough,DemiÃ¡n Bichir,John Cho,"Horror, Mystery, Thriller",The Grudge,Andrea Riseborough DemiÃ¡n Bichir John Cho Nico...
1,William Eubank,Kristen Stewart,Vincent Cassel,Jessica Henwick,"Action, Horror, Sci-Fi, Thriller",Underwater,Kristen Stewart Vincent Cassel Jessica Henwick...
2,Miguel Arteta,Tiffany Haddish,Rose Byrne,Salma Hayek,Comedy,Like a Boss,Tiffany Haddish Rose Byrne Salma Hayek Miguel ...
3,Jon Avnet,Richard Gere,Peter Dinklage,Walton Goggins,Drama,Three Christs,Richard Gere Peter Dinklage Walton Goggins Jon...
4,Anthony Jerjen,Josh Hartnett,Margarita Levieva,Chandler Riggs,"Crime, Drama, Thriller",Inherit the Viper,Josh Hartnett Margarita Levieva Chandler Riggs...
...,...,...,...,...,...,...,...
265,Robert Rodriguez,Priyanka Chopra Jonas,Pedro Pascal,YaYa Gosselin,Comedy,We Can Be Heroes,Priyanka Chopra Jonas Pedro Pascal YaYa Gossel...
266,Paul Greengrass,Tom Hanks,Helena Zengel,NaN,"Action, Adventure, Drama, Western",News of the World,NaN
267,Regina King,Kingsley Ben-Adir,Eli Goree,Aldis Hodge,Drama,One Night in Miami,Kingsley Ben-Adir Eli Goree Aldis Hodge Regina...
268,Emerald Fennell,Carey Mulligan,Bo Burnham,Alison Brie,"Crime, Drama, Thriller",Promising Young Woman,Carey Mulligan Bo Burnham Alison Brie Emerald ...
269,KornÃ©l MundruczÃ³,Vanessa Kirby,Shia LaBeouf,Molly Parker,NaN,Pieces of a Woman,NaN

In [160]:
link = "https://en.wikipedia.org/wiki/List_of_Bollywood_films_of_2020"
df1 = pd.read_html(link, header=0)[2]
df2 = pd.read_html(link, header=0)[3]
df3 = pd.read_html(link, header=0)[4]
df4 = pd.read_html(link, header=0)[5]

In [156]:
df_b = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

In [157]:
df_b

,Opening,Opening.1,Title,Director,Cast,Studio (production house),Ref.
0,JAN,1.0,Ghost Stories,Karan JoharDibakar BanerjeeZoya AkhtarAnurag K...,Sobhita DhulipalaMrunal ThakurAvinash TiwaryJa...,"RSVP Movies, Flying Unicorn Entertainment, Net...",[13]
1,JAN,3.0,Bhangra Paa Le,Sneha Taurani,Sunny KaushalRukshar DhillonShriya Pilgaonkar,RSVP Movies,[14]
2,JAN,3.0,Sab Kushal Mangal,Karan Vishwanath Kashyap,Akshaye KhannaRiva KishanPriyank Sharma,One Up Entertainment,[15]
3,JAN,3.0,Shimla Mirchi,Ramesh Sippy,Hema MaliniRajkummar RaoRakul Preet Singh,Viacom18 Motion Pictures,[16]
4,JAN,10.0,Chhapaak,Meghna Gulzar,Deepika PadukoneVikrant Massey,"Fox Star Studios, Ka Productions, Mriga Films",[17]
...,...,...,...,...,...,...,...
94,DEC,18.0,Omprakash Zindabad,Ranjeet Gupta,Kulbhushan KharbandaJagdeepShweta BhardwajSeem...,Panorama Studios,[109]
95,DEC,18.0,Unpaused,Raj & D.KNitya MehraNikkhil AdvaniTannishtha C...,Gulshan DevaiahSumeet VyasSaiyami KherRicha Ch...,Amazon Prime Video,[110]
96,DEC,24.0,AK vs AK,Vikramaditya Motwane,Anil KapoorAnurag Kashyap,Netflix,[111]
97,DEC,25.0,Coolie No. 1,David Dhawan,Varun DhawanSara Ali Khan,"Pooja Entertainment, Amazon Prime Video",[97]
98,DEC,25.0,Shakeela,Indrajit Lankesh,Richa ChaddaPankaj TripathiRajeev Pillai,Sammy's Magic Cinema,[112]

In [161]:
from omdbapi.movie_search import GetMovie
import json
import requests

In [162]:
genres = []
for i in range(99):
    movie = GetMovie(title=df_b['Title'][i], api_key='e3fc1d3f', plot='full')
    data = movie.get_data('Genre')
    genres.append(data)

In [163]:
from pandas import DataFrame
df4 = DataFrame(genres,columns=['Genre'])

In [164]:
df_b['genres'] = df4

In [165]:
df_b['Cast and crew'] = df_b['Cast']

In [166]:
df_en = df_b[['Title','Director','Cast and crew','genres']]

In [167]:
df_en['Cast and crew'] = df_en['Cast and crew'].str.replace( r"([A-Z])", r" \1").str.strip()

<ipython-input-167-add6444aa4b9>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_en['Cast and crew'] = df_en['Cast and crew'].str.replace( r"([A-Z])", r" \1").str.strip()

In [168]:
df_en

,Title,Director,Cast and crew,genres
0,Ghost Stories,Karan JoharDibakar BanerjeeZoya AkhtarAnurag K...,Sobhita Dhulipala Mrunal Thakur Avinash Tiw...,"Drama, Horror"
1,Bhangra Paa Le,Sneha Taurani,Sunny Kaushal Rukshar Dhillon Shriya Pilgao...,"Comedy, Drama, Music"
2,Sab Kushal Mangal,Karan Vishwanath Kashyap,Akshaye Khanna Riva Kishan Priyank Sharma,Romance
3,Shimla Mirchi,Ramesh Sippy,Hema Malini Rajkummar Rao Rakul Preet Singh,"Comedy, Romance"
4,Chhapaak,Meghna Gulzar,Deepika Padukone Vikrant Massey,"Biography, Drama"
...,...,...,...,...
94,Omprakash Zindabad,Ranjeet Gupta,Kulbhushan Kharbanda Jagdeep Shweta Bhardwaj...,key not found!
95,Unpaused,Raj & D.KNitya MehraNikkhil AdvaniTannishtha C...,Gulshan Devaiah Sumeet Vyas Saiyami Kher Ri...,"Drama, Romance"
96,AK vs AK,Vikramaditya Motwane,Anil Kapoor Anurag Kashyap,"Comedy, Drama, Thriller"
97,Coolie No. 1,David Dhawan,Varun Dhawan Sara Ali Khan,Comedy
98,Shakeela,Indrajit Lankesh,Richa Chadda Pankaj Tripathi Rajeev Pillai,"Biography, Drama"

In [170]:
df_en.to_csv("2020_Movies.csv")

In [171]:
df10 = pd.read_csv("2020_Movies_cleaned.csv")
df10.head()

,Unnamed: 0,movie_title,director_name,Cast and crew,genres,actor_1_name,actor_2_name,actor_3_name
0,0,Ghost Stories,Karan JoharDibakar BanerjeeZoya AkhtarAnurag K...,Sobhita Dhulipala Mrunal Thakur Avinash Tiw...,"Drama, Horror",Sobhita Dhulipala,Mrunal Thakur,Gulshan Devaiah
1,1,Bhangra Paa Le,Sneha Taurani,Sunny Kaushal Rukshar Dhillon Shriya Pilgao...,"Comedy, Drama, Music",Sunny Kaushal,Rukshar Dhillon,Shriya Pilgaonkar
2,2,Sab Kushal Mangal,Karan Vishwanath Kashyap,Akshaye Khanna Riva Kishan Priyank Sharma,Romance,Akshaye Khanna,Riva Kishan,Priyank Sharma
3,3,Shimla Mirchi,Ramesh Sippy,Hema Malini Rajkummar Rao Rakul Preet Singh,"Comedy, Romance",Hema Malini,Rajkummar Rao,Rakul Preet Singh
4,4,Chhapaak,Meghna Gulzar,Deepika Padukone Vikrant Massey,"Biography, Drama",Deepika Padukone,Vikrant Massey,NaN

In [172]:
hnew_df20 = df10.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [173]:
hnew_df20

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title
0,Karan JoharDibakar BanerjeeZoya AkhtarAnurag K...,Sobhita Dhulipala,Mrunal Thakur,Gulshan Devaiah,"Drama, Horror",Ghost Stories
1,Sneha Taurani,Sunny Kaushal,Rukshar Dhillon,Shriya Pilgaonkar,"Comedy, Drama, Music",Bhangra Paa Le
2,Karan Vishwanath Kashyap,Akshaye Khanna,Riva Kishan,Priyank Sharma,Romance,Sab Kushal Mangal
3,Ramesh Sippy,Hema Malini,Rajkummar Rao,Rakul Preet Singh,"Comedy, Romance",Shimla Mirchi
4,Meghna Gulzar,Deepika Padukone,Vikrant Massey,NaN,"Biography, Drama",Chhapaak
...,...,...,...,...,...,...
93,Ranjeet Gupta,Kulbhushan Kharbanda,Shweta Bhardwaj,Om Puri,Drama,Omprakash Zindabad
94,Raj & D.KNitya MehraNikkhil AdvaniTannishtha C...,Gulshan Devaiah,Sumeet Vyas,Richa Chadha,"Drama, Romance",Unpaused
95,Vikramaditya Motwane,Anil Kapoor,Anurag Kashyap,Sonam Kapoor,"Comedy, Drama, Thriller",AK vs AK
96,David Dhawan,Varun Dhawan,Sara Ali Khan,Javed Jaffery,Comedy,Coolie No. 1
97,Indrajit Lankesh,Richa Chadda,Pankaj Tripathi,Rajeev Pillai,"Biography, Drama",Shakeela

In [175]:
hnew_df20['actor_2_name'] = hnew_df20['actor_2_name'].replace(np.nan, 'unknown')
hnew_df20['actor_3_name'] = hnew_df20['actor_3_name'].replace(np.nan, 'unknown')
hnew_df20['movie_title'] = hnew_df20['movie_title'].str.lower()

In [176]:
hnew_df20['comb'] = hnew_df20['actor_1_name'] + ' ' + hnew_df20['actor_2_name'] + ' '+ hnew_df20['actor_3_name'] + ' '+ hnew_df20['director_name'] +' ' + hnew_df20['genres']

In [177]:
hnew_df20

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Karan JoharDibakar BanerjeeZoya AkhtarAnurag K...,Sobhita Dhulipala,Mrunal Thakur,Gulshan Devaiah,"Drama, Horror",ghost stories,Sobhita Dhulipala Mrunal Thakur Gulshan Dev...
1,Sneha Taurani,Sunny Kaushal,Rukshar Dhillon,Shriya Pilgaonkar,"Comedy, Drama, Music",bhangra paa le,Sunny Kaushal Rukshar Dhillon Shriya Pilgao...
2,Karan Vishwanath Kashyap,Akshaye Khanna,Riva Kishan,Priyank Sharma,Romance,sab kushal mangal,Akshaye Khanna Riva Kishan Priyank Sharma K...
3,Ramesh Sippy,Hema Malini,Rajkummar Rao,Rakul Preet Singh,"Comedy, Romance",shimla mirchi,Hema Malini Rajkummar Rao Rakul Preet Sing...
4,Meghna Gulzar,Deepika Padukone,Vikrant Massey,unknown,"Biography, Drama",chhapaak,Deepika Padukone Vikrant Massey unknown Megh...
...,...,...,...,...,...,...,...
93,Ranjeet Gupta,Kulbhushan Kharbanda,Shweta Bhardwaj,Om Puri,Drama,omprakash zindabad,Kulbhushan Kharbanda Shweta Bhardwaj Om Puri...
94,Raj & D.KNitya MehraNikkhil AdvaniTannishtha C...,Gulshan Devaiah,Sumeet Vyas,Richa Chadha,"Drama, Romance",unpaused,Gulshan Devaiah Sumeet Vyas Richa Chadha Ra...
95,Vikramaditya Motwane,Anil Kapoor,Anurag Kashyap,Sonam Kapoor,"Comedy, Drama, Thriller",ak vs ak,Anil Kapoor Anurag Kashyap Sonam Kapoor Vikr...
96,David Dhawan,Varun Dhawan,Sara Ali Khan,Javed Jaffery,Comedy,coolie no. 1,Varun Dhawan Sara Ali Khan Javed Jaffery Da...
97,Indrajit Lankesh,Richa Chadda,Pankaj Tripathi,Rajeev Pillai,"Biography, Drama",shakeela,Richa Chadda Pankaj Tripathi Rajeev Pillai ...

In [205]:
df_2020 = new_df20.append(hnew_df20,ignore_index=True)

In [206]:
df_2020

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Nicolas Pesce,Andrea Riseborough,DemiÃ¡n Bichir,John Cho,"Horror, Mystery, Thriller",The Grudge,Andrea Riseborough DemiÃ¡n Bichir John Cho Nico...
1,William Eubank,Kristen Stewart,Vincent Cassel,Jessica Henwick,"Action, Horror, Sci-Fi, Thriller",Underwater,Kristen Stewart Vincent Cassel Jessica Henwick...
2,Miguel Arteta,Tiffany Haddish,Rose Byrne,Salma Hayek,Comedy,Like a Boss,Tiffany Haddish Rose Byrne Salma Hayek Miguel ...
3,Jon Avnet,Richard Gere,Peter Dinklage,Walton Goggins,Drama,Three Christs,Richard Gere Peter Dinklage Walton Goggins Jon...
4,Anthony Jerjen,Josh Hartnett,Margarita Levieva,Chandler Riggs,"Crime, Drama, Thriller",Inherit the Viper,Josh Hartnett Margarita Levieva Chandler Riggs...
...,...,...,...,...,...,...,...
363,Ranjeet Gupta,Kulbhushan Kharbanda,Shweta Bhardwaj,Om Puri,Drama,omprakash zindabad,Kulbhushan Kharbanda Shweta Bhardwaj Om Puri...
364,Raj & D.KNitya MehraNikkhil AdvaniTannishtha C...,Gulshan Devaiah,Sumeet Vyas,Richa Chadha,"Drama, Romance",unpaused,Gulshan Devaiah Sumeet Vyas Richa Chadha Ra...
365,Vikramaditya Motwane,Anil Kapoor,Anurag Kashyap,Sonam Kapoor,"Comedy, Drama, Thriller",ak vs ak,Anil Kapoor Anurag Kashyap Sonam Kapoor Vikr...
366,David Dhawan,Varun Dhawan,Sara Ali Khan,Javed Jaffery,Comedy,coolie no. 1,Varun Dhawan Sara Ali Khan Javed Jaffery Da...
367,Indrajit Lankesh,Richa Chadda,Pankaj Tripathi,Rajeev Pillai,"Biography, Drama",shakeela,Richa Chadda Pankaj Tripathi Rajeev Pillai ...

In [207]:
df_2020.to_csv("2020_Films_All.csv")

In [209]:
old_df = pd.read_csv('new_data.csv')
old_df = old_df.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title', 'comb']]

In [210]:
old_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakensÂ ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
5359,Jim Strouse,Jessica Williams,Chris O'Dowd,Keith Stanfield,Romance Comedy,the incredible jessica james,Jessica Williams Chris O'Dowd Keith Stanfield ...
5360,Farhad Mann,Adelaide Kane,Benjamin Hollingsworth,Jean Louisa Kelly,Romance,can't buy my love,Adelaide Kane Benjamin Hollingsworth Jean Loui...
5361,Hannaleena Hauru,Inka HaapamÃ¤ki,Rosa Honkonen,Tiitus Rantala,Romance Comedy,thick lashes of lauri mÃ¤ntyvaara,Inka HaapamÃ¤ki Rosa Honkonen Tiitus Rantala Ha...
5362,Jonathan A. Rosenbaum,Lou Diamond Phillips,Wallace Shawn,Gina Holden,Crime Comedy Action Family,cop and a half: new recruit,Lou Diamond Phillips Wallace Shawn Gina Holden...
5363,Ravi Udyawar,Sridevi Kapoor,Sajal Ali,Akshaye Khanna,Crime Drama Thriller,mom,Sridevi Kapoor Sajal Ali Akshaye Khanna Ravi U...

In [221]:
df2 = pd.read_csv("2018_Films_All.csv")
df3 = pd.read_csv("2019_Films_All.csv")
df4 = pd.read_csv("2020_Films_All.csv")

In [222]:
final_df = old_df.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

In [223]:
final_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb,Unnamed: 0
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...,NaN
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...,NaN
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...,NaN
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...,NaN
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakensÂ ...,Doug Walker Rob Walker unknown Doug Walker Doc...,NaN
...,...,...,...,...,...,...,...,...
6463,Ranjeet Gupta,Kulbhushan Kharbanda,Shweta Bhardwaj,Om Puri,Drama,omprakash zindabad,Kulbhushan Kharbanda Shweta Bhardwaj Om Puri...,363.0
6464,Raj & D.KNitya MehraNikkhil AdvaniTannishtha C...,Gulshan Devaiah,Sumeet Vyas,Richa Chadha,"Drama, Romance",unpaused,Gulshan Devaiah Sumeet Vyas Richa Chadha Ra...,364.0
6465,Vikramaditya Motwane,Anil Kapoor,Anurag Kashyap,Sonam Kapoor,"Comedy, Drama, Thriller",ak vs ak,Anil Kapoor Anurag Kashyap Sonam Kapoor Vikr...,365.0
6466,David Dhawan,Varun Dhawan,Sara Ali Khan,Javed Jaffery,Comedy,coolie no. 1,Varun Dhawan Sara Ali Khan Javed Jaffery Da...,366.0
6467,Indrajit Lankesh,Richa Chadda,Pankaj Tripathi,Rajeev Pillai,"Biography, Drama",shakeela,Richa Chadda Pankaj Tripathi Rajeev Pillai ...,367.0

In [224]:
final_df.isna().sum()

director_name       0
actor_1_name        1
actor_2_name        3
actor_3_name       26
genres              5
movie_title         0
comb               31
Unnamed: 0       5364
dtype: int64

In [228]:
final_df[final_df['actor_1_name'].isnull()].index.tolist()

[5681]

In [230]:
final_df['actor_1_name'].isnull().sum()

1

In [237]:
final_df['actor_1_name'].fillna("Unknown", inplace=True)
final_df['actor_2_name'].fillna("Unknown", inplace=True)
final_df['actor_3_name'].fillna("Unknown", inplace=True)
final_df['genres'].fillna("Drama", inplace=True)

In [238]:
final_df = final_df.drop('Unnamed: 0',axis=1)

In [239]:
final_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakensÂ ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
6463,Ranjeet Gupta,Kulbhushan Kharbanda,Shweta Bhardwaj,Om Puri,Drama,omprakash zindabad,Kulbhushan Kharbanda Shweta Bhardwaj Om Puri...
6464,Raj & D.KNitya MehraNikkhil AdvaniTannishtha C...,Gulshan Devaiah,Sumeet Vyas,Richa Chadha,"Drama, Romance",unpaused,Gulshan Devaiah Sumeet Vyas Richa Chadha Ra...
6465,Vikramaditya Motwane,Anil Kapoor,Anurag Kashyap,Sonam Kapoor,"Comedy, Drama, Thriller",ak vs ak,Anil Kapoor Anurag Kashyap Sonam Kapoor Vikr...
6466,David Dhawan,Varun Dhawan,Sara Ali Khan,Javed Jaffery,Comedy,coolie no. 1,Varun Dhawan Sara Ali Khan Javed Jaffery Da...
6467,Indrajit Lankesh,Richa Chadda,Pankaj Tripathi,Rajeev Pillai,"Biography, Drama",shakeela,Richa Chadda Pankaj Tripathi Rajeev Pillai ...

In [240]:
final_df.isna().sum()

director_name     0
actor_1_name      0
actor_2_name      0
actor_3_name      0
genres            0
movie_title       0
comb             31
dtype: int64

In [241]:
final_df = final_df.dropna(how='any')

In [242]:
final_df.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      0
comb             0
dtype: int64

In [245]:
final_df.to_csv('main_data.csv',index=False)

In [246]:
final_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakensÂ ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
6463,Ranjeet Gupta,Kulbhushan Kharbanda,Shweta Bhardwaj,Om Puri,Drama,omprakash zindabad,Kulbhushan Kharbanda Shweta Bhardwaj Om Puri...
6464,Raj & D.KNitya MehraNikkhil AdvaniTannishtha C...,Gulshan Devaiah,Sumeet Vyas,Richa Chadha,"Drama, Romance",unpaused,Gulshan Devaiah Sumeet Vyas Richa Chadha Ra...
6465,Vikramaditya Motwane,Anil Kapoor,Anurag Kashyap,Sonam Kapoor,"Comedy, Drama, Thriller",ak vs ak,Anil Kapoor Anurag Kashyap Sonam Kapoor Vikr...
6466,David Dhawan,Varun Dhawan,Sara Ali Khan,Javed Jaffery,Comedy,coolie no. 1,Varun Dhawan Sara Ali Khan Javed Jaffery Da...
6467,Indrajit Lankesh,Richa Chadda,Pankaj Tripathi,Rajeev Pillai,"Biography, Drama",shakeela,Richa Chadda Pankaj Tripathi Rajeev Pillai ...